# Generated by Django 3.2.3 on 2021-08-25 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('appname', models.CharField(max_length=128)),
                ('logo', models.FileField(blank=True, null=True, upload_to='media/')),
                ('slug', models.SlugField(max_length=128, unique_for_date='publish')),
                ('category', models.CharField(choices=[('Trading', 'trading'), ('E-commerce', 'e-commerce'), ('Socialmedia', 'socialmedia')], default='trading', max_length=11)),
                ('description', models.TextField()),
                ('andriod_link', models.CharField(max_length=10000)),
                ('andriod_rate', models.FloatField()),
                ('ios_link', models.CharField(blank=True, max_length=10000, null=True)),
                ('ios_rate', models.FloatField(blank=True, null=True)),
                ('publish', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-no'],
            },
        ),
    ]
